<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"用户管理",
                       "menuJump":"列表",
                       "tableName":"yonghu"
                   }
               ],
               "menu":"用户管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"员工管理",
                       "menuJump":"列表",
                       "tableName":"yuangong"
                   }
               ],
               "menu":"员工管理"
           }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"订单管理",
                        "menuJump":"列表",
                        "tableName":"dingdan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"售后服务管理",
                        "menuJump":"列表",
                        "tableName":"dingdanLiuyan"
                    }
                ],
                "menu":"订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			    ],
			    "menu":"公告类型管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "支付",
	                        "生产",
	                        "生产成功",
	                        "删除"
	                    ],
	                    "menu":"订单管理",
	                    "menuJump":"列表",
	                    "tableName":"dingdan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"售后服务管理",
	                    "menuJump":"列表",
	                    "tableName":"dingdanLiuyan"
	                }
	            ],
	            "menu":"订单管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yuangong"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "支付",
	                        "收货",
	                        "查看评论",
	                        "删除"
	                    ],
	                    "menu":"订单管理",
	                    "menuJump":"列表",
	                    "tableName":"dingdan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"售后服务管理",
	                    "menuJump":"列表",
	                    "tableName":"dingdanLiuyan"
	                }
	            ],
	            "menu":"订单管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
